spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MinIO配置
minio:
  endpoint: http://yuanbaocat.work:9000  # 替换为您的MinIO服务器IP
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: testbucket
# 服务端口
server:
  port: 8888

logging:
  level:
    sql: debug